name: Build Development Installer
on:
    push:
        branches: [master]
        tags-ignore:
            - "**"
jobs:
    build:
        strategy:
            matrix:
                platform: [ windows-latest ]
                go-version: [1.18]
        runs-on: ${{ matrix.platform }}
        steps:
        - uses: actions/checkout@v2
        - name: Install Go
          uses: actions/setup-go@v2
          with:
              go-version: ${{ matrix.go-version }}
        - name: setup node
          uses: actions/setup-node@v2
          with:
              node-version: 16
        - run: cd frontend && npm install && npm run build
        - name: Get Wails
          run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
        - name: Build app
          run: |
              New-Item -ItemType SymbolicLink -Target "$PWD" -Path "$env:GOROOT\src\extension-installer"
              wails build -webview2 embed
        - name: Sign Windows binaries
          if: matrix.platform == 'windows-latest'
          run: |
              echo "Creating certificate file"
              New-Item -ItemType directory -Path certificate
              Set-Content -Path certificate\certificate.txt -Value '${{ secrets.WIN_SIGNING_CERT }}'
              certutil -decode certificate\certificate.txt certificate\certificate.pfx
              echo "Signing our binaries"
              & 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.22000.0/x86/signtool.exe' sign /fd SHA256 /tr "http://timestamp.sectigo.com" /td SHA256 /f certificate\certificate.pfx build/bin/lumeweb-extension-installer.exe

        - name: Add SHORT_SHA env property with commit short sha
          run: echo "SHORT_SHA=$($env:GITHUB_SHA[1..8] | out-string -nonewline)" |  Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        - name: Publish Build
          uses: softprops/action-gh-release@v0.1.14
          with:
              prerelease: true
              files: "build/bin/lumeweb-extension-installer.exe"
              tag_name: "dev-${{ env.SHORT_SHA }}"
              name: "dev-${{ env.SHORT_SHA }}"
